### ISSUE TITLE
Lodge Reservation (Book your vacation) Page Prototype

### ISSUE THREAD

**Issue by CesarJoel04** [CesarJoel04/Moffat-Bay#10]
Create prototype: As a logged-in user, I want to book my vacation by selecting room size, number of guests, and check-in/check-out dates so that I can plan my stay at Moffat Bay Lodge.

Story Points: 2

**Comment by shivemind** [comment]
![Image](https://github.com/CesarJoel04/Moffat-Bay/assets/7762327/e0b3b2fd-224e-4e6c-ad0a-e8d9b21e79a1)
