### ISSUE TITLE
Reservation Summary Page Prototype

### ISSUE THREAD

**Issue by CesarJoel04** [CesarJoel04/Moffat-Bay#11]
Create prototype: As a user who has booked a reservation, I want to view a summary of my booking with the option to confirm or cancel the reservation so that I can finalize my plans.

Story Points: 2

**Comment by sbachma** [comment]
![Image](https://github.com/CesarJoel04/Moffat-Bay/assets/94061452/610e8e3a-db1f-42d6-983e-09c370c06f69)
