### ISSUE TITLE
Populate Database - Moffat Bay Project

### ISSUE THREAD

**Issue by CesarJoel04** [CesarJoel04/Moffat-Bay#14]
Populate Database for the Moffat Bay project

Have at least 3 entries

**Comment by shivemind** [comment]
INSERT INTO Customers (email, first_name, last_name, telephone, password_hash) VALUES 
('alice@example.com', 'Alice', 'Wonderland', '555-0101', 'passhash1'),
('bob@example.com', 'Bob', 'Builder', '555-0102', 'passhash2'),
('charlie@example.com', 'Charlie', 'Brown', '555-0103', 'passhash3'),
('diana@example.com', 'Diana', 'Prince', '555-0104', 'passhash4');

INSERT INTO Rooms (room_size, availability) VALUES 
('double_full', 10),
('queen', 8),
('double_queen', 5),
('king', 3);

INSERT INTO GuestPricing (min_guests, max_guests, price_per_night) VALUES 
(1, 1, 100.00),
(2, 2, 180.00),
(3, 4, 250.00),
(5, 6, 300.00);
