### ISSUE TITLE
Create Database - Moffat Bay Project

### ISSUE THREAD

**Issue by CesarJoel04** [CesarJoel04/Moffat-Bay#15]
Create Database for the Moffat Bay project

**Comment by ptheerthagiribellevue** [comment]
I have successfully finished the database task and all queries have been executed without errors. The database scripts have been attached for your reference.

[MoffetBay_DBScripts.txt](https://github.com/CesarJoel04/Moffat-Bay/files/14899739/MoffetBay_DBScripts.txt)
