### ISSUE TITLE
Sam Bachman - Testing and Quality Assurance

### ISSUE THREAD

**Issue by sbachma** [CesarJoel04/Moffat-Bay#17]
Conduct thorough testing of all functionalities, including guest browsing, user registration/login, booking, and reservation lookup.

Story Points: 8

**Comment by sbachma** [comment]
[TestPlanTemplate (2).docx](https://github.com/CesarJoel04/Moffat-Bay/files/14973246/TestPlanTemplate.2.docx)

**Comment by CesarJoel04** [comment]
@sbachma  Let keep this story open until all testing are done.
