### ISSUE TITLE
Create Test Plan - Module 7 & 8

### ISSUE THREAD

**Issue by CesarJoel04** [CesarJoel04/Moffat-Bay#24]
- Write 4 functional tests for Room Reservation Page
- Write 2 functional tests for About Us Page
- Write 2 functional tests for Reservation Summary Page

**Comment by sbachma** [comment]
[TestPlanTemplate.pdf](https://github.com/CesarJoel04/Moffat-Bay/files/15057702/TestPlanTemplate.pdf)
