### ISSUE TITLE
About Us Page Prototype

### ISSUE THREAD

**Issue by CesarJoel04** [CesarJoel04/Moffat-Bay#5]
Create a prototype: As a user, I want to read about the history, mission, and team behind Moffat Bay Lodge on the About Us page so that I can understand more about the lodge's background and values.

Story Points: 2

**Comment by ptheerthagiribellevue** [comment]
![Image](https://github.com/CesarJoel04/Moffat-Bay/assets/127821150/f3e37a96-41fd-4b98-99d0-cecc2ae20fd7)
