### ISSUE TITLE
Attractions Page Prototype

### ISSUE THREAD

**Issue by CesarJoel04** [CesarJoel04/Moffat-Bay#7]
Create prototype: As a user, I want to explore the various attractions around Moffat Bay Lodge, including hiking, kayaking, whale watching, and scuba diving, on the Attractions page so that I can plan activities during my stay.

Story Points: 2

**Comment by shivemind** [comment]
![Image](https://github.com/CesarJoel04/Moffat-Bay/assets/7762327/5c7a9535-6a54-4b86-b173-d71d912834ac)
