### ISSUE TITLE
Registration Page Prototype

### ISSUE THREAD

**Issue by CesarJoel04** [CesarJoel04/Moffat-Bay#8]
Create prototype: As a new user, I want to register an account with my email, first name, last name, telephone, and password so that I can log in and book my vacation.

Story Points: 2

**Comment by ptheerthagiribellevue** [comment]
![Image](https://github.com/CesarJoel04/Moffat-Bay/assets/127821150/ddac56b5-3556-4ff3-8c69-b08ace21b0ab)
