### ISSUE TITLE
Login Page Prototype

### ISSUE THREAD

**Issue by CesarJoel04** [CesarJoel04/Moffat-Bay#9]
Create a prototype: As a user, I want to log in using my email and password so that I can access my account and book a vacation.

Story Points: 2

**Comment by shivemind** [comment]
![Image](https://github.com/CesarJoel04/Moffat-Bay/assets/7762327/94223716-45dc-4344-8d66-6df95b7796cf)

**Comment by shivemind** [comment]
![Image](https://github.com/CesarJoel04/Moffat-Bay/assets/7762327/ac83db22-265c-484e-a093-51f47b24b93d)

**Comment by sbachma** [comment]
![Image](https://github.com/CesarJoel04/Moffat-Bay/assets/94061452/83cac37b-b1f1-4167-942a-4967b7cb651a)
